language: go

go:
  - 1.4.2
  - 1.5.3
  - tip

before_install:
    - uname -a
    - go get golang.org/x/tools/cmd/vet
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/golang/lint/golint
    - go get github.com/mattn/goveralls
    - go get github.com/funny/utest
    - go get github.com/funny/crypto/aes256cbc
    - go get github.com/funny/reuseport

install:
    - go get -d -v ./... && go build -v ./...

script:
    - go vet -x ./...
    - $HOME/gopath/bin/golint ./...
    - go test -v -covermode=count -coverprofile=profile.cov

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
    - go test -benchmem -bench .
